### ISSUE TITLE
HomePage: Content: Sign Up/Sign In

### ISSUE THREAD

**Issue by ClaytonAndTheClayTones** [mva3212/code#6]
To assist in attracting new accounts, there should be a content space on the homepage that, when a session is not signed in, give the user a very obvious interface for signing up, and perhaps a less obvious one for signing in.  Like "SIGN UP! with some fields and underneath them, a link in normal sized text "already a member? sign in" that routes to the normal login page.   This is redundant with the login/logout/signup partial view, but a majority of similar membership-based sites do this early on...

**Comment by mva3212** [comment]
agree, i'd like to keep the membership form to only email, password and confirmation.  all additional information can be added by filling out your "profile" once an account is created, similar to how linked in does it.

**Comment by mva3212** [comment]
this is accomplished via the navbar sign in dropdown and the redirects on user level access pages
